sudo: false

language: python

python:
   - 2.7
   - 3.5

addons:
  apt:
    packages:
      - gnuplot

cache: pip

notifications:
  email: false

install:
   - pip install nose-cov
   - pip install coveralls
   - pip install IPython[notebook]
   - pip install metakernel
   - python setup.py install

script:
   - make test

after_success:
   - coveralls --rcfile=.coveragerc
